### ISSUE TITLE
Build fails with JDK 27-ea+17

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#5605]
https://github.com/junit-team/junit-framework/actions/runs/24383901286/job/71213196133

Build used to work with JDK 27-ea+16.

```
/home/runner/work/junit-framework/junit-framework/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/DynamicTestTestDescriptor.java:65: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
> Task :junit-jupiter-engine:compileJava
		ExtensionContext extensionContext = context.getExtensionContext();
		                                           ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following, as well as a reproducing code sample (if possible):
  
     error-prone version: 2.48.0
     BugPattern: NullAway
     Stack Trace:
     org.checkerframework.nullaway.javacutil.BugInCF: Problem with initial store for CFGMethod(
  
  @Override
  public JupiterEngineExecutionContext execute(JupiterEngineExecutionContext context, DynamicTestExecutor dynamicTestExecutor) {
      DynamicTestInvocationContext dynamicTestInvocationContext = new DefaultDynamicTestInvocationContext(requiredDynamicTest().getExecutable());
      ExtensionContext extensionContext = context.getExtensionContext();
      ExtensionRegistry extensionRegistry = context.getExtensionRegistry();
      interceptorChain.<@Nullable Void>invoke(toInvocation(), extensionRegistry, InterceptorCall.ofVoid((InvocationInterceptor interceptor, InvocationInterceptor.Invocation<@Nullable Void> wrappedInvocation)->interceptor.interceptDynamicTest(wrappedInvocation, dynamicTestInvocationContext, extensionContext)));
      return context;
  }
  ), parameters=[context, dynamicTestExecutor]
    	at org.checkerframework.nullaway.dataflow.analysis.ForwardAnalysisImpl.initInitialInputs(ForwardAnalysisImpl.java:351)
    	at org.checkerframework.nullaway.dataflow.analysis.AbstractAnalysis.init(AbstractAnalysis.java:554)
    	at org.checkerframework.nullaway.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:102)
    	at com.uber.nullaway.dataflow.RunOnceForwardAnalysisImpl.performAnalysis(RunOnceForwardAnalysisImpl.java:31)
    	at com.uber.nullaway.dataflow.DataFlow.dataflow(DataFlow.java:163)
    	at com.uber.nullaway.dataflow.DataFlow.resultFor(DataFlow.java:329)
    	at com.uber.nullaway.dataflow.DataFlow.resultForExpr(DataFlow.java:307)
    	at com.uber.nullaway.dataflow.DataFlow.expressionDataflow(DataFlow.java:230)
    	at com.uber.nullaway.dataflow.AccessPathNullnessAnalysis.getNullness(AccessPathNullnessAnalysis.java:119)
    	at com.uber.nullaway.NullAway.nullnessFromDataflow(NullAway.java:2724)
    	at com.uber.nullaway.NullAway.mayBeNullExpr(NullAway.java:2692)
    	at com.uber.nullaway.NullAway.matchDereference(NullAway.java:2752)
    	at com.uber.nullaway.NullAway.matchMemberSelect(NullAway.java:610)
    	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:541)
[...]
    	at java.base/java.lang.Thread.run(Thread.java:1527)
    Caused by: java.lang.Throwable
    	at org.checkerframework.nullaway.javacutil.BugInCF.<init>(BugInCF.java:26)
    	... 114 more
  1 error

* Try:
> Check your code and dependencies to fix the compilation error(s)

BUILD FAILED in 1m 29s

Publishing Build Scan to Develocity...
gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-scans/__self_2-1776147111462.json
https://ge.junit.org/s/qnhwhk6toc2qc
```

**Comment by mpkorstanje** [comment]
After updating `error_prone_core` to v2.49.0 in https://github.com/junit-team/junit-framework/pull/5589 the problem goes away but https://github.com/uber/NullAway/issues/1534 does arise.

**Comment by marcphilipp** [comment]
Shall we close this issue for the time being? Renovate and the build will let us know when it's resolved.
